define("containerjs/utils/deferred",[],function(){var g={then:function(b,a){},always:function(b){},done:function(b){},fail:function(b){},pipe:function(b,a){},fixed:function(){},rejected:function(){},resolved:function(){}},c=function(){this.state=d.unresolved;this.result=null;this.successCallbacks=[];this.failCallbacks=[];Object.seal(this)};c.prototype.then=function(b,a){var h=new c;this.state.done.call(this,b,h);this.state.fail.call(this,a,h);return h};c.prototype.always=function(b){return this.then(b,
b)};c.prototype.done=function(b){var a=new c;this.state.done.call(this,b,a);return a};c.prototype.fail=function(b){var a=new c;this.state.fail.call(this,b,a);return a};c.prototype.resolve=function(b){this.state.resolve.call(this,b);return this};c.prototype.reject=function(b){this.state.reject.call(this,b);return this};c.prototype.fixed=function(){return this.rejected()||this.resolved()};c.prototype.rejected=function(){return this.state===d.rejected};c.prototype.resolved=function(){return this.state===
d.resolved};c.prototype.promise=function(){return Object.freeze({then:this.then.bind(this),done:this.done.bind(this),fail:this.fail.bind(this),always:this.always.bind(this),pipe:this.pipe.bind(this),fixed:this.fixed.bind(this),rejected:this.rejected.bind(this),resolved:this.resolved.bind(this)})};c.prototype.pipe=function(b,a){var h=new c;this.then(function(d){try{h.resolve(b?b(d):d)}catch(c){h.reject(a?a(c):c)}},function(b){try{b=a?a(b):b}catch(d){}h.reject(b)});return h.promise()};c.valueOf=function(b){var a=
new c;a.resolve(b);return a.promise()};c.errorOf=function(b){var a=new c;a.reject(b);return a.promise()};c.when=function(b){var a=new c,h=[];if(0===b.length)a.resolve(h);else{var d=b.length,e=function(b){a.fixed()||a.reject(b)};b.forEach(function(b,c){b.then(function(b){h[c]=b;0!==--d||a.fixed()||a.resolve(h)},e)})}return a.promise()};c.isPromise=function(b){for(var a in g)if(!b[a])return!1;return!0};c.pack=function(b,a,h){var d=new c;try{var e=b.apply(a,h);if(c.isPromise(e))return e;d.resolve(e)}catch(f){d.reject(f)}return d.promise()};
c.unpack=function(b){var a=null,h=null;b.then(function(b){a=b},function(a){h=a});if(h)throw h;return a};c.defer=function(b){return function(){return c.pack(b,this,arguments)}};c.lazy=function(b,a,h){var e=new c,l=function(){try{var d=b.apply(a,h);c.isPromise(d)?d.then(function(a){e.resolve(a)},function(a){e.reject(a)}):e.resolve(d)}catch(l){e.reject(l)}};e.state={done:function(a,b){d.unresolved.done.apply(this,arguments);this.state=d.unresolved;l()},fail:function(a,b){d.unresolved.fail.apply(this,
arguments);this.state=d.unresolved;l()},resolve:d.unresolved.resolve,reject:d.unresolved.reject};return e};var f=function(){throw Error("already resolved or rejected.");},k=function(b,a){var h,d;h=0;for(d=b.length;h<d;h++)b[h].call(null,a)},e=function(b,a){return function(h){try{var d=b(h);a.resolve(d)}catch(e){a.reject(e)}}},d={unresolved:{done:function(b,a){this.successCallbacks.push(e(b,a));return a},fail:function(b,a){this.failCallbacks.push(e(b,a));return a},resolve:function(b){this.result=b;
this.state=d.resolved;k(this.successCallbacks,b);this.successCallbacks=void 0},reject:function(b){this.result=b;this.state=d.rejected;k(this.failCallbacks,b);this.failCallbacks=void 0}},resolved:{done:function(b,a){e(b,a)(this.result)},fail:function(b,a){},resolve:f,reject:f},rejected:{done:function(b,a){},fail:function(b,a){e(b,a)(this.result)},resolve:f,reject:f}};return c});
define("containerjs/loader",["containerjs/utils/deferred"],function(g){return Object.freeze({load:function(c){var f=new g;try{require([c],function(e){f.resolve(e)},function(e){f.reject(e)})}catch(k){f.reject(k)}return f}})});
define("containerjs/scope",["containerjs/utils/deferred"],function(g){var c=function(c,e,d){return c.singletonComponents[e.id]||(c.singletonComponents[e.id]=c.createComponent(e,d))},f=function(c,e){var d=c.singletonComponents[e.id];d&&g.unpack(d.then(function(b){e.destroy(b,c)}))},c={SINGLETON:Object.freeze({retrievingStrategy:c,destructionStrategy:f,createOnStartUp:!1}),EAGER_SINGLETON:Object.freeze({retrievingStrategy:c,destructionStrategy:f,createOnStartUp:!0}),PROTOTYPE:Object.freeze({retrievingStrategy:function(c,
e,d){return c.createComponent(e,d)},destructionStrategy:function(c,e){},createOnStartUp:!1})};return Object.freeze(c)});define("containerjs/key",["containerjs/utils/deferred"],function(g){var c={get:function(c){},create:function(f,k,e){return Object.freeze(Object.create(c,{get:{value:function(d,b){b=e?null:b;var a=k?d.gets(f,b):d.get(f,b);return e?g.valueOf(a):a}}}))}};Object.freeze(c);return c});
define("containerjs/inject",["containerjs/key"],function(g){var c=function(c){return g.create(c,!1,!1)};c.lazily=function(c){return g.create(c,!1,!0)};c.all=function(c){return g.create(c,!0,!1)};c.all.lazily=function(c){return g.create(c,!0,!0)};Object.freeze(c);return c});
define("containerjs/utils/asserts",[],function(){var g={assertNotNull:function(c,g){if(null==c)throw Error(g+" is null or undefined.");},assertNotEmpty:function(c,f){g.assertNotNull(c,f);if(""===c)throw Error(f+" is empty string.");},assertValueIsFunction:function(c,f){g.assertNotNull(c,f);if("function"!==typeof c)throw Error(f+" is not function.");}};return Object.freeze(g)});
define("containerjs/bindings/binding",["containerjs/inject","containerjs/key","containerjs/scope","containerjs/utils/asserts","containerjs/utils/deferred"],function(g,c,f,k,e){var d=function(b){k.assertNotNull(b.id,"id");k.assertNotEmpty(b.name,"name");this.id=b.id;this.name=b.name;this.scope=b.scope||f.SINGLETON;this.injectionProperties=b.injectionProperties||{};this.destructor=this.initializer=void 0};d.prototype.getInstance=function(b,a){};d.prototype.initialize=function(b,a){this.initializer&&
this.initializer(b,a)};d.prototype.destroy=function(b,a){this.destructor&&this.destructor(b,a)};d.prototype.injectProperties=function(b,a,h){var d=this.collectInjectionProperties(b);return this.resolveProperties(d,a,null,h).pipe(function(a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b}.bind(this))};d.prototype.collectInjectionProperties=function(b){var a={};this.collectFromModuleDefinition(a,this.injectionProperties);this.collectFromComponent(a,b);return a};d.prototype.collectFromModuleDefinition=
function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};d.prototype.collectFromComponent=function(b,a){for(var d in a){var c=a[d];this.isInjectionProperty(c)&&(b[d]=c)}};d.prototype.isInjectionProperty=function(b){return b&&c.isPrototypeOf(b)?!0:b===g||b===g.all||b===g.lazily||b===g.all.lazily?!0:!1};d.prototype.resolveProperty=function(b,a,d,f){return b&&c.isPrototypeOf(b)?b.get(a,f):b===g||b===g.all||b===g.lazily||b===g.all.lazily?(k.assertNotNull(d,"name"),b(d).get(a,f)):e.valueOf(b)};d.prototype.resolveProperties=
function(b,a,d,c){var l=[];if(!b)return e.valueOf(b);if(b.forEach)return b.forEach(function(b){l.push(this.resolveProperty(b,a,c))}),e.wait(l);var g=[],f;for(f in b)b.hasOwnProperty(f)&&(g.push(f),l.push(this.resolveProperty(d?b[f][d]:b[f],a,f,c)));return e.when(l).pipe(function(a){for(var c={},e=0;e<g.length;e++){var l=g[e];d?(b[l][d]=a[e],c[l]=b[l]):c[l]=a[e]}return c})};Object.seal(d.prototype);return d});
define("containerjs/packaging-policy",["containerjs/utils/asserts","containerjs/utils/deferred"],function(g,c){var f={retrieve:c.defer(function(d,b,a){g.assertNotEmpty(b,"componentName");a=a||this.resolveModuleFor(b);g.assertNotEmpty(a,"moduleName");return d.load(a).pipe(function(d){if(!(d=d&&this.findComponent(d,b)))throw Error("componenet '"+b+"' is not found in module '"+a+"'.");return d}.bind(this))})},k={};k.MODULE_PER_PACKAGE=Object.freeze(Object.create(f,function(){var d=function(b){if(/^\\.+$/.test(b))throw Error("invalid component name. componentName\x3d"+
String(b));};return{resolveModuleFor:{value:function(b){d(b);var a=b.lastIndexOf(".");if(-1===a||a+1>=b.length)throw Error("componentName does not contain a package.");b=b.substring(0,b.lastIndexOf("."));return e(b)}},findComponent:{value:function(b,a){var c;d(a);c=a.substring(a.lastIndexOf(".")+1);return b[c]}}}}()));k.MODULE_PER_CLASS=Object.freeze(Object.create(f,{resolveModuleFor:{value:function(d){return e(d)}},findComponent:{value:function(d,b){return d}}}));k.SINGLE_FILE=Object.freeze(Object.create(f,
{resolveModuleFor:{value:function(d){return e(d.split(".")[0])}},findComponent:{value:function(d,b){for(var a=b.split("."),c=d,e=1;e<a.length&&c;e++)c=c[a[e]];return c}}}));k.DEFAULT=k.MODULE_PER_CLASS;var e=function(d){return d.replace(/\./g,"/").replace(/([a-z])(?=[A-Z])/g,"$1-").toLowerCase()};return Object.freeze(k)});
define("containerjs/bindings/module-binding",["containerjs/bindings/binding","containerjs/packaging-policy"],function(g,c){var f=function(f){this.module=f.module||void 0;this.packagingPolicy=f.packagingPolicy||c.DEFAULT};f.prototype=Object.create(g.prototype);f.prototype.load=function(c){return this.packagingPolicy.retrieve(c,this.componentName(),this.module)};f.prototype.componentName=function(){};Object.seal(f.prototype);return f});
define("containerjs/bindings/prototype-binding",["containerjs/bindings/binding","containerjs/bindings/module-binding","containerjs/utils/asserts","containerjs/utils/deferred"],function(g,c,f,k){var e=function(d){f.assertNotNull(d.prototype,"prorotype");g.call(this,d);c.call(this,d);this.prototype=d.prototype;this.prototypeProperties=d.prototypeProperties||void 0};e.prototype=Object.create(c.prototype);e.prototype.getInstance=function(d,b){var a=new k,c=function(b){a.reject(b)};this.load(d.loader).then(function(e){this.resolveProperties(this.prototypeProperties,
d,"value",b).then(function(l){var f=Object.create(e,l);this.injectProperties(f,d,b).then(function(){a.resolve(f)},c).fail(c)}.bind(this),c).fail(c)}.bind(this),c).fail(c);return a};e.prototype.componentName=function(){return this.prototype};e.prototype.resolvePrototypeProperties=function(d,b){var a={},c;for(c in d)a[c]=this.resolve(d[c].value,b,c);return a};Object.freeze(e.prototype);return e});
define("containerjs/bindings/constructor-binding",["containerjs/bindings/binding","containerjs/bindings/module-binding","containerjs/utils/asserts","containerjs/utils/deferred"],function(g,c,f,k){var e=function(d){f.assertNotNull(d.constructor,"constructor");g.call(this,d);c.call(this,d);this.constructor=d.constructor;this.constructorArgument=d.constructorArgument||void 0};e.prototype=Object.create(c.prototype);e.prototype.getInstance=function(d,b){var a=new k,c=function(b){a.reject(b)};this.load(d.loader).then(function(e){this.resolveProperties(this.constructorArgument,
d,null,b).then(function(f){var g=new e(f);this.injectProperties(g,d,b).then(function(){a.resolve(g)},c).fail(c)}.bind(this),c).fail(c)}.bind(this),c).fail(c);return a};e.prototype.componentName=function(){return this.constructor};Object.freeze(e.prototype);return e});
define("containerjs/bindings/object-binding",["containerjs/bindings/binding","containerjs/bindings/module-binding","containerjs/utils/asserts","containerjs/utils/deferred"],function(g,c,f,k){var e=function(d){f.assertNotNull(d.object,"object");g.call(this,d);c.call(this,d);this.object=d.object};e.prototype=Object.create(c.prototype);e.prototype.getInstance=function(d,b){var a=new k,c=function(b){a.reject(b)};this.load(d.loader).then(function(e){this.injectProperties(e,d,b).then(function(){a.resolve(e)},
c).fail(c)}.bind(this),c).fail(c);return a};e.prototype.componentName=function(){return this.object};Object.freeze(e.prototype);return e});define("containerjs/bindings/instance-binding",["containerjs/bindings/binding","containerjs/utils/deferred"],function(g,c){var f=function(c){g.call(this,c);this.instance=c.instance};f.prototype=Object.create(g.prototype);f.prototype.getInstance=function(c,e){return this.injectProperties(this.instance,c,e)};Object.freeze(f.prototype);return f});
define("containerjs/bindings/provider-binding",["containerjs/bindings/binding","containerjs/utils/deferred","containerjs/utils/asserts"],function(g,c,f){c=function(c){f.assertValueIsFunction(c.provider,"provider");g.call(this,c);this.provider=c.provider};c.prototype=Object.create(g.prototype);c.prototype.getInstance=function(c){return this.injectProperties(this.provider(c),c)};Object.freeze(c.prototype);return c});
define("containerjs/bindings/binding-factory",["containerjs/bindings/prototype-binding","containerjs/bindings/constructor-binding","containerjs/bindings/object-binding","containerjs/bindings/instance-binding","containerjs/bindings/provider-binding"],function(g,c,f,k,e){var d=function(b){return{value:function(a){a.id=this.serial++;return Object.seal(new b(a))}}};return Object.seal(Object.create({createPrototypeBinding:function(b){},createConstructorBinding:function(b){},createObjectBinding:function(b){},
createInstanceBinding:function(b){},createPrvoiderBinding:function(b){}},{createPrototypeBinding:d(g),createConstructorBinding:d(c),createObjectBinding:d(f),createInstanceBinding:d(k),createProviderBinding:d(e),serial:{value:0,writable:!0}}))});
define("containerjs/binding-builders",["containerjs/bindings/binding-factory"],function(g){var c={to:function(a){this.reference.set(g.createConstructorBinding({name:this.reference.get().name,constructor:a,packagingPolicy:this.reference.get().packagingPolicy}));return b(m,this.reference)},toPrototype:function(a,c){this.reference.set(g.createPrototypeBinding({name:this.reference.get().name,prototype:a,prototypeProperties:c,packagingPolicy:this.reference.get().packagingPolicy}));return b(h,this.reference)},
asPrototype:function(a){this.reference.set(g.createPrototypeBinding({name:this.reference.get().name,prototype:this.reference.get().name,prototypeProperties:a,packagingPolicy:this.reference.get().packagingPolicy}));return b(h,this.reference)},toObject:function(a){this.reference.set(g.createObjectBinding({name:this.reference.get().name,object:a,packagingPolicy:this.reference.get().packagingPolicy}));return b(h,this.reference)},asObject:function(){this.reference.set(g.createObjectBinding({name:this.reference.get().name,
object:this.reference.get().name,packagingPolicy:this.reference.get().packagingPolicy}));return b(h,this.reference)},toInstance:function(a){this.reference.set(g.createInstanceBinding({name:this.reference.get().name,instance:a}));return b(e,this.reference)},toProvider:function(a){this.reference.set(g.createProviderBinding({name:this.reference.get().name,provider:a}));return b(e,this.reference)}},f={withConstructorArgument:function(a){this.reference.get().constructorArgument=a;return b(h,this.reference)}},
k={loadFrom:function(a,b){this.reference.get().module=a;return this},assign:function(a){a&&(this.reference.get().packagingPolicy=a);return this}},e={withProperties:function(a){this.reference.get().injectionProperties=a;return this},onInitialize:function(a){this.reference.get().initializer=d(a);return this},onDestroy:function(a){this.reference.get().destructor=d(a);return this},inScope:function(a){this.reference.get().scope=a;return this}},d=function(a){return"string"===typeof a?function(b,c){b[a](b)}:
function(b,c){a.call(null,b)}},b=function(a,b){return Object.freeze(Object.create(a,{reference:{value:b}}))},a=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b],e;for(e in d)a[e]=d[e]}return a},h=a(e,k),m=a(f,h),a=a(c,m);Object.freeze(c);Object.freeze(f);Object.freeze(e);Object.freeze(k);Object.freeze(a);Object.freeze(m);Object.freeze(h);return{RootBuilder:a}});
define("containerjs/aspect",[],function(){var g=function(c,d){this.interceptor=c;this.matcher=d;Object.freeze(this)},c=g.prototype;c.weave=function(c,d){var b=this.isEnhancedObject(d)?Object.getPrototypeOf(d):d,a={};return this.collectAndCreateEnhancedMethod(c,d,b,a)?(a[k]={value:!0},Object.create(d,a)):d};c.collectAndCreateEnhancedMethod=function(c,d,b,a){var h=this.collectFromEnumerableProperties(c,d,b,a);return this.collectFromNonEnumerableProperties(c,d,b,a)||h};c.collectFromEnumerableProperties=
function(c,d,b,a){var h=!1,f;for(f in b)h=this.checkAndCreateEnhancedMethod(c,d,a,f)||h;return h};c.collectFromNonEnumerableProperties=function(c,d,b,a){var h=!1;Object.getOwnPropertyNames(b).forEach(function(f){Object.getOwnPropertyDescriptor(b,f).enumerable||(h=this.checkAndCreateEnhancedMethod(c,d,a,f)||h)}.bind(this));var f=Object.getPrototypeOf(b);f&&(h=this.collectFromNonEnumerableProperties(c,d,f,a)||h);return h};c.checkAndCreateEnhancedMethod=function(c,d,b,a){if("function"===typeof d[a]&&
(!this.matcher||this.matcher(c,d,a))){c=d[a];if(this.isEnhancedMethod(c))return c[f].push(this.interceptor),!1;if(this.isEnhancedObject(d))return Object.defineProperty(d,a,this.createEnhancedMethod(d,a)),!1;b[a]=this.createEnhancedMethod(d,a);return!0}};c.createEnhancedMethod=function(c,d){var b=c[d],a=[this.interceptor],h=function(){var c=0,e=[];e.push.apply(e,arguments);var f=Object.freeze({self:this,methodName:d,proceed:function(){return c<a.length?a[c++].call(null,f):b.apply(f.self,f.arguments)},
arguments:e,context:{}});return f.proceed()};h[f]=a;return{value:h}};c.isEnhancedMethod=function(c){return!!c[f]};c.isEnhancedObject=function(c){return!!c[k]};var f="$ContainerJS.interceptors",k="$ContainerJS.enhanced";return g});
define("containerjs/binder",["containerjs/scope","containerjs/bindings/binding-factory","containerjs/binding-builders","containerjs/packaging-policy","containerjs/aspect"],function(g,c,f,k,e){var d;g=function(a){this.bindings={};this.aspects=[];this.defaultPackagingPolicy=a||k.DEFAULT;Object.freeze(this)};var b=g.prototype;b.bind=function(a){var b=this.getBindingsFor(a),b=Object.freeze(Object.create(d,{bindings:{value:b},index:{value:b.length}}));b.set(c.createConstructorBinding({name:a,constructor:a,
packagingPolicy:this.defaultPackagingPolicy}));return Object.freeze(Object.create(f.RootBuilder,{reference:{value:b}}))};b.bindInterceptor=function(a,b){this.aspects.push(new e(a,b))};b.setDefaultPackagingPolicy=function(a){this.defaultPackagingPolicy=a;return this};b.buildBindings=function(){var a,b,c;for(b in this.bindings)if(this.bindings.hasOwnProperty(b)){var d=this.bindings[b];a=0;for(c=d.length;a<c;a++)Object.freeze(d[a])}return this.bindings};b.buildAspects=function(){return this.aspects};
b.getBindingsFor=function(a){return this.bindings[a]||(this.bindings[a]=[])};d={index:-1,bindings:[],set:function(a){this.bindings[this.index]=a},get:function(){return this.bindings[this.index]}};Object.freeze(g.prototype);return g});
define("containerjs/container",["containerjs/loader","containerjs/binder","containerjs/scope","containerjs/utils/deferred"],function(g,c,f,k){f=function(a,b){this.creating={};this.singletonComponents={};this.chainedContainer=null;this.createRequestSerial=1;this.load(a,b);this.loader=g;this.onEagerSingletonConponentsInitialized=this.createEagerSingletonConponents(this);Object.seal(this)};var e=f.prototype;e.get=function(a,b){return k.lazy(d,this,arguments)};var d=function(a,b){var c=null;try{c=this.getBinding(a)}catch(d){return this.chainedContainer?
this.chainedContainer.get(a):k.errorOf(d)}try{this.checkCyclicDependency(c,b)}catch(e){return k.errorOf(e)}return c.scope.retrievingStrategy(this,c,b)};e.gets=function(a,c){return k.lazy(b,this,arguments)};var b=function(a,b){var c=null;try{c=this.getBindings(a)}catch(d){return this.chainedContainer?this.chainedContainer.gets(a):k.errorOf(d)}var e=null;try{e=c.map(function(a){this.checkCyclicDependency(a,b);return a.scope.retrievingStrategy(this,a,b)}.bind(this))}catch(f){return k.errorOf(f)}if(this.chainedContainer&&
this.chainedContainer.hasBindings(a)){var g=new k,n=function(a){g.reject(a)};k.when(e).then(function(b){this.chainedContainer.gets(a).then(function(a){g.resolve(b.concat(a))},n)}.bind(this),n);return g}return k.when(e)};e.getBinding=function(a){return this.getBindings(a)[0]};e.getBindings=function(a){if(this.hasBindings(a))return this.bindings[a];throw Error("component is not binded. name\x3d"+a);};e.hasBindings=function(a){return(a=this.bindings[a])&&0<a.length};e.destroy=function(){for(var a in this.bindings)this.bindings[a].forEach(function(a){a.scope.destructionStrategy(this,
a)}.bind(this)),delete this.singletonComponents[a]};e.chain=function(a){this.chainedContainer=a};e.createComponent=k.defer(function(a,b){var c=this.createRequestSerial++;this.creating[c]={id:a.id,name:a.name,parentId:b};return a.getInstance(this,c).pipe(function(b){try{return this.aspects.forEach(function(c){b=c.weave(a,b)}),a.initialize(b,this),b}finally{delete this.creating[c]}}.bind(this),function(a){delete this.creating[c];return a}.bind(this))});e.checkCyclicDependency=function(a,b){for(var c=
[a.name];b;){c.unshift(this.creating[b].name);if(this.creating[b].id===a.id)throw Error("detect cyclic dependency.\n  -\x3e "+c.join("\n  -\x3e "));b=this.creating[b].parentId}};e.load=function(a,b){var d=new c(b);a.call(null,d);this.bindings=d.buildBindings();this.aspects=d.buildAspects()};e.createEagerSingletonConponents=function(){var a=function(a){return a.scope.createOnStartUp?a.scope.retrievingStrategy(this,a):null}.bind(this),b=[],c;for(c in this.bindings)b=b.concat(this.bindings[c].map(a).filter(function(a){return null!=
a}));return k.when(b)};Object.freeze(e);return f});define("container",["containerjs/container","containerjs/scope","containerjs/inject","containerjs/packaging-policy","containerjs/utils/deferred"],function(g,c,f,k,e){g={VERSION:"1.0.0",Container:g,Scope:c,Inject:f,PackagingPolicy:k,utils:Object.freeze({Deferred:e})};Object.freeze(g);return g});